<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-7IK17HP" failures="1" tests="4" name="PersonalDetails" time="0.273" errors="0" timestamp="2020-08-31T17:16:50 IST">
  <testcase classname="bank.loan.PersonalDetails" name="familyDetails" time="0.022"/>
  <testcase classname="bank.loan.PersonalDetails" name="familyDetails" time="0.004"/>
  <testcase classname="bank.loan.PersonalDetails" name="familyDetails" time="0.007"/>
  <testcase classname="bank.loan.PersonalDetails" name="hobies" time="0.029">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at bank.loan.PersonalDetails.hobies(PersonalDetails.java:24)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- hobies -->
</testsuite> <!-- PersonalDetails -->
